### ISSUE TITLE
This action is completely broken

### ISSUE THREAD

**Issue by Janealter** [atlassian/gajira-find-issue-key#7] opened 2020-02-25 18:00 UTC
- `string` parameter doesn't work because it is not processed in the source code
- `this.argv._.join(' ')` - this also doesn't work because `argv` doesn't contain `_`

**Has anyone ever checked this code?)**

**Comment by rudzon** [comment] 2020-10-21 08:19
Hi @Janealter! The issue is fixed in the latest release https://github.com/atlassian/gajira-find-issue-key/releases/tag/v2.0.2

**Closed as completed by rudzon** 2020-10-21 08:19 UTC
